version: '3.1'

services:
  db:
    container_name: app-db
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'Travels'
      MYSQL_HOST: 'localhost'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 20s
      retries: 10

  app:
    container_name: app-travels
    build: .
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    command: java -jar travels-java-api-0.0.1-SNAPSHOT.jar
    ports:
      - '8080:8080'
    volumes:
      - .:/home/app
    environment:
      DATABASE_URL: 'jdbc:mysql://host.docker.internal:3306/Travels'
      DATABASE_USERNAME: 'admin'
      DATABASE_PASSWORD: 'admin'
